[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv"]

[phases.install]
cmds = [
    "python3 -m venv venv",
    "source venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "source venv/bin/activate && uvicorn server:app --host 0.0.0.0 --port $PORT"
cwd = "backend" 